
const PRODUCTS=window.MINAS_PRODUCTS||[];
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function getCart(){try{return JSON.parse(localStorage.getItem('minasCart')||'{}')}catch{return{}}}
function saveCart(c){localStorage.setItem('minasCart',JSON.stringify(c));updateCount()}
function updateCount(){const c=getCart(); const n=Object.values(c).reduce((a,b)=>a+Number(b||0),0); $$('[data-cart-count]').forEach(e=>e.textContent=n)}
function addCart(id,qty=1){const c=getCart();c[id]=(c[id]||0)+Number(qty||1);saveCart(c);alert('Produto adicionado ao carrinho da prévia.');}
function card(p){return `<article class="product-card"><a class="product-image" href="produto.html?id=${p.id}"><img src="${esc(p.image)}" alt="${esc(p.name)}"></a><div class="product-body"><div class="product-meta"><span>${esc(p.brand)}</span><span>${esc(p.sku)}</span></div><h3><a href="produto.html?id=${p.id}">${esc(p.name)}</a></h3><div class="availability">● ${esc(p.availability)}</div><div class="locked">Cadastre-se ou entre para visualizar preços</div><div class="card-actions"><a class="btn ghost full" href="produto.html?id=${p.id}">Ver produto</a><button class="btn primary full" data-add="${p.id}">Adicionar ao carrinho</button></div></div></article>`}
function renderGrid(){const g=$('[data-product-grid]');if(!g)return;let list=PRODUCTS.filter(p=>p.status==='active');const params=new URLSearchParams(location.search);const q=(($('#catalogSearch')?.value)||params.get('q')||'').toLowerCase().trim();const cat=($('#catalogCategory')?.value)||params.get('cat')||'';if(q)list=list.filter(p=>[p.name,p.sku,p.brand,p.category].join(' ').toLowerCase().includes(q));if(cat)list=list.filter(p=>p.category===cat);const lim=Number(g.dataset.limit||0);if(lim)list=list.filter(p=>p.featured).slice(0,lim);g.innerHTML=list.map(card).join('')||'<div class="cart-empty">Nenhum produto encontrado.</div>';$$('[data-add]',g).forEach(b=>b.onclick=()=>addCart(b.dataset.add,1));}
function categories(){const el=$('[data-categories]');const sel=$('#catalogCategory');const counts={};PRODUCTS.filter(p=>p.status==='active').forEach(p=>counts[p.category]=(counts[p.category]||0)+1);if(el)el.innerHTML=Object.entries(counts).map(([c,n])=>`<a class="category" href="produtos.html?cat=${encodeURIComponent(c)}"><b>${esc(c)}</b><span>${n} produtos →</span></a>`).join('');if(sel){Object.keys(counts).forEach(c=>sel.insertAdjacentHTML('beforeend',`<option value="${esc(c)}">${esc(c)}</option>`));const p=new URLSearchParams(location.search);if(p.get('cat'))sel.value=p.get('cat');sel.onchange=renderGrid;}}
function productDetail(){const el=$('[data-product-detail]');if(!el)return;const id=Number(new URLSearchParams(location.search).get('id')||1);const p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[0];$('[data-product-breadcrumb]').textContent=p.name;el.innerHTML=`<div class="detail-image"><img src="${esc(p.image)}" alt="${esc(p.name)}"></div><div class="detail-copy"><span class="eyebrow">${esc(p.category)}</span><h1>${esc(p.name)}</h1><div class="sku">Marca ${esc(p.brand)} • SKU ${esc(p.sku)}</div><div class="availability">● ${esc(p.availability)}</div><p class="desc">${esc(p.description)}</p><div class="detail-spec"><b>Informações do produto</b><p>${esc(p.specs)}</p></div><div class="detail-lock"><b>Preço comercial protegido</b><p>Cadastre sua empresa ou entre para visualizar a tabela correspondente ao seu perfil.</p><a class="btn secondary" href="cadastro.html">Cadastrar empresa</a></div><div class="qty-line"><input id="detailQty" type="number" min="1" value="1"><button class="btn primary" id="detailAdd">Adicionar ao carrinho</button></div></div>`;$('#detailAdd').onclick=()=>addCart(p.id,Number($('#detailQty').value||1));const rel=$('[data-related]');if(rel)rel.innerHTML=PRODUCTS.filter(x=>x.category===p.category&&x.id!==p.id).slice(0,4).map(card).join('');$$('[data-add]',rel).forEach(b=>b.onclick=()=>addCart(b.dataset.add,1));}
function cartView(){const el=$('[data-cart-view]');if(!el)return;const c=getCart();const items=Object.entries(c).map(([id,q])=>({p:PRODUCTS.find(x=>x.id===Number(id)),q:Number(q)})).filter(x=>x.p&&x.q>0);if(!items.length){el.innerHTML='<div class="cart-empty"><h2>Seu carrinho está vazio.</h2><p>Explore o catálogo e adicione produtos para montar sua solicitação.</p><a class="btn primary" href="produtos.html">Ver produtos</a></div>';return;}el.innerHTML=`<div class="cart-list">${items.map(({p,q})=>`<div class="cart-item"><img src="${esc(p.image)}" alt=""><div><h3>${esc(p.name)}</h3><p>SKU ${esc(p.sku)} • ${esc(p.category)}</p><p>Preço disponível após aprovação cadastral</p></div><input type="number" min="1" value="${q}" data-qty="${p.id}"><button class="remove-btn" data-remove="${p.id}">Remover</button></div>`).join('')}</div><div class="cart-summary-static"><div><b>${items.length} produto(s) diferente(s)</b><p>A versão final exibirá valores e total para clientes aprovados.</p></div><a class="btn primary" href="cadastro.html">Cadastrar para liberar preços</a></div>`;$$('[data-qty]').forEach(i=>i.onchange=()=>{const c=getCart();c[i.dataset.qty]=Math.max(1,Number(i.value||1));saveCart(c)});$$('[data-remove]').forEach(b=>b.onclick=()=>{const c=getCart();delete c[b.dataset.remove];saveCart(c);cartView()});}
function demoForms(){$$('[data-demo-form]').forEach(f=>f.onsubmit=e=>{e.preventDefault();f.hidden=true;const s=f.parentElement.querySelector('.demo-success');if(s)s.hidden=false});const l=$('[data-demo-login]');if(l)l.onsubmit=e=>{e.preventDefault();alert('Login real será ativado na versão de produção. Esta página é apenas uma prévia navegável.')}}
function customerType(){const p=new URLSearchParams(location.search);const s=$('#customerType');if(s&&p.get('tipo')==='revenda')s.value='reseller'}
document.addEventListener('DOMContentLoaded',()=>{updateCount();categories();const s=$('#catalogSearch');if(s){s.value=new URLSearchParams(location.search).get('q')||'';s.oninput=renderGrid}renderGrid();productDetail();cartView();demoForms();customerType()});
